# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: indigo

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    # org_name: ''
    # description: 'A data science and statistical research expert specializing in probabilistic modeling, extreme value analysis, and practical solutions for real-world challenges.'
    #twitter: ''
  analytics:
    google_analytics: 'G-FJNQQVNHJ3'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "V-logo.png"
    #button:
    #  enable: true
    #  text: "Get Started"
    #  url: "https://hugoblox.com/templates/"
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: 'This website is marked <a href="https://creativecommons.org/publicdomain/zero/1.0/">CC0 1.0</a><img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/zero.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;">'
  widgets:
    - id: links
      text: ""
      links:
        - icon: github
          icon_pack: fab
          text: GitHub
          url: https://github.com/rainonsnow.vincenzocoia.com
        # - icon: envelope
          # icon_pack: fas
          # text: Email
          # url: mailto:vincenzo.coia@gmail.com
  background:
    color: "white"
    text_color_light: false

# Localization
locale:
  date_format: '2 Jan 2006'
  time_format: '3:04 PM'
